// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  //will keep this to later use for react web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoKNNN9vLU4qDSjyyJJhgsx2T8aYKzbJE',
    appId: '1:637846106040:web:3077621ef063c2a056694d',
    messagingSenderId: '637846106040',
    projectId: 'pet-on-app',
    authDomain: 'pet-on-app.firebaseapp.com',
    storageBucket: 'pet-on-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvldSwcAV7P5Y4m1uQWODskAKiCkvgOyU',
    appId: '1:637846106040:android:e543186dee3003a456694d',
    messagingSenderId: '637846106040',
    projectId: 'pet-on-app',
    storageBucket: 'pet-on-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeH1Uru8q28qScQgj7TOJklWRyIuhVn6M',
    appId: '1:637846106040:ios:20147f1f7200e9dd56694d',
    messagingSenderId: '637846106040',
    projectId: 'pet-on-app',
    storageBucket: 'pet-on-app.firebasestorage.app',
    iosBundleId: 'on.pet.peton',
  );
}
